[package]
name = "Roblox-assets-extractor"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
eframe = "0.28.1"
egui = "0.28.1"
egui_dock = "0.13.0"
fluent-bundle = "0.15.3"
image = "0.25.5"
lazy_static = "1.5.0"
native-dialog = "0.7.0"
open = "5.3.0"
reqwest = "0.12.9"
serde_json = "1.0.133"
sys-locale = "0.3.2"
tempfile = "3"
unic-langid = "0.9.5"
whoami = "1.5.2"

[build-dependencies]
winresource = "0.1.17"

# Minimize executable size (Target size < 10MB)
[target.'cfg(not(windows))'.profile.release.package."*"] # Exclude this on Windows as this somehow false-triggers Windows Defender...
opt-level = "z"
codegen-units = 1
debug = false
overflow-checks = false

[profile.release]
opt-level = 3 # Main search logic in this project, opt-level 3 for speed
codegen-units = 1
lto = "fat"
debug = false
panic = "abort"
overflow-checks = false
