name: Build and Release

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.rs"
      - "**.toml"
      - "**.ftl"
      - "assets/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.rs"
      - "**.toml"
      - "**.ftl"
      - "assets/**"
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose --release
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-bin
          path: target/release/RoExtract.exe

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose --release
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-bin
          path: target/release/RoExtract

  create-release:
    needs: [windows-build, linux-build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Get timestamp
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
      
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-bin
          path: artifacts/windows

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-bin
          path: artifacts/linux

      - name: Rename binaries
        run: |
          mv artifacts/windows/RoExtract.exe artifacts/windows/RoExtract-windows.exe
          mv artifacts/linux/RoExtract artifacts/linux/RoExtract-linux

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev-build-${{ github.run_id }}
          name: "Development Build (${{ steps.date.outputs.date }})"
          body: |
            Development preview build - Bugs may appear, if you are looking to just use the software, use the [latest stable release](https://github.com/AeEn123/RoExtract/releases/latest)
            - Commit: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            - Build date: ${{ steps.date.outputs.date }}
          prerelease: true
          files: |
            artifacts/windows/RoExtract-windows.exe
            artifacts/linux/RoExtract-linux
