name: Linux Build

on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Upload build
      uses: actions/upload-artifact@v4.4.3
      with:
        path: ${{github.workspace}}/target/release/Roblox-assets-extractor
