name: Windows Build

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.rs"
      - "**.toml"
      - "**.ftl"
      - "assets/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.rs"
      - "**.toml"
      - "**.ftl"
      - "assets/**"
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Upload build
      uses: actions/upload-artifact@v4.4.3
      with:
        path: ${{github.workspace}}/target/release/Roblox-assets-extractor.exe
